* Base64 encoder/decoder
This is a utility that attempts to simulate the basic functionality of a common CLI tool called [[https://command-not-found.com/base64][base64]]. It's an opportunity also to test out a build tool other than [[https://command-not-found.com/cmake][Cmake]].

* Requirements
[[https://mesonbuild.com/][Meson]] is the only dependency required a build tool meant for extremely fast and user-friendly project builds. It's the first time I ever try to use it. Due to the relative simplicity of this project, I decided it was more than suitable as first crack at it.

* Installing Meson
The meson official site provides clear instructions on how to install the build tool for all platforms. I have been working on both a =GNU/Debian= and =NixOS= system for base64.

- For GNU/Debian users
#+begin_src sh
  sudo apt update
  sudo apt install meson
#+end_src
- For NixOS users
This is a flake configuration. I trust if you're a NixOS user that you know what you need to do if flakes are too experimental for you and use something else.
#+begin_src sh
  environment.systemPackages = pkgs [
    # packages
    python313Packages.meson
    # more packages
  ];
#+end_src
#+begin_src sh
  # To install
  nix --extra-experimental-features \
    nix-command --extra-experimental-features \
    flakes run nix-darwin -- switch --flake .#$USER
#+end_src

* Building
The library is built both statically and dynamically. All one needs to do is run a couple =meson= commands. The =bin= directory is where I personally store all my builds since it's more along [[https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard][The Filesystem Hierarchy Standard]].
- To setup the build direcotry
#+begin_src sh
  meson setup bin
#+end_src

- To compile the library
#+begin_src sh
  cd bin && meson compile
#+end_src

- To run the main.c example
#+begin_src sh
  PATH_TO_FILE=~/Photos/sample.png
  cd bin && ./base64 $PATH_TO_FILE
#+end_src


* Documentation
- To encode a file into base64.
#+begin_src c
  char file_name = "file.txt";
  char file_content[1<<16];
  ssize_t size = read_from_file(file_name, file_content); /* file_content = "I love the way you lie"; */
  char *encoding = encode(file_content, size);
  printf("Encoding: %s\n", encoding); /* Encoding: SSBsb3ZlIHRoZSB3YXkgeW91IGxpZQo= */
  free(encoding);
#+end_src

- To decode a base64 encoded buffer.
#+begin_src c
  char buffer[1<<16] = "SSBsb3ZlIHRoZSB3YXkgeW91IGxpZQo=";
  size_t size = strlen(buffer);
  char *decoding = decode(buffer, size);
  printf("Decoding: %s\n", decoding); /* Decoding: I love the way you lie */
  free(decoding);
#+end_src
